# Generated by Django 5.2.12 on 2026-04-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_agegroup_title_alter_agegroup_slug_alter_brand_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='category/icons/'),
        ),
    ]
