# Generated by Django 5.2.12 on 2026-04-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='statusorder',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
