# Generated by Django 5.2.12 on 2026-04-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('delivery_text', models.TextField(blank=True)),
                ('warranty_text', models.TextField(blank=True)),
            ],
        ),
    ]
